-- 코드를 입력하세요
SELECT R.FOOD_TYPE, REST_ID, REST_NAME, R.FAVORITES
FROM REST_INFO R
JOIN 
    (SELECT FOOD_TYPE, MAX(FAVORITES) AS M
    FROM REST_INFO
    GROUP BY FOOD_TYPE) AS I
ON R.FAVORITES = I.M
    AND
   R.FOOD_TYPE = I.FOOD_TYPE
ORDER BY R.FOOD_TYPE DESC