-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT USER_ID) AS USERS
FROM
    (SELECT ONLINE_SALE_ID, SALES_DATE, U.GENDER, U.USER_ID
    FROM ONLINE_SALE O
    JOIN USER_INFO U
    ON O.USER_ID = U.USER_ID) AS T
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER