-- 코드를 입력하세요
SELECT C.CAR_ID, ROUND(C.AD, 1) AS AVERAGE_DURATION
FROM
    (SELECT CAR_ID, AVG(DATEDIFF(END_DATE, START_DATE) + 1) AS AD
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
    HAVING AD >= 7) AS C
ORDER BY AVERAGE_DURATION DESC, C.CAR_ID DESC