-- 코드를 입력하세요
SELECT O.PRODUCT_ID, P.PRODUCT_NAME, O.AMOUNT * P.PRICE
FROM     
    (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
    GROUP BY PRODUCT_ID) AS O
JOIN
    FOOD_PRODUCT P
ON O.PRODUCT_ID = P.PRODUCT_ID
ORDER BY O.AMOUNT * P.PRICE DESC, O.PRODUCT_ID ASC