-- 코드를 입력하세요
SELECT P.CATEGORY, P.PRICE, P.PRODUCT_NAME
FROM FOOD_PRODUCT P
JOIN 
    (SELECT MAX(PRICE) AS M
    FROM FOOD_PRODUCT F
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
    ORDER BY PRICE DESC) S
ON P.PRICE = S.M
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY P.PRICE DESC