SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE, 
       (SELECT PRODUCT_NAME 
        FROM FOOD_PRODUCT FP2 
        WHERE FP2.CATEGORY = FP1.CATEGORY AND FP2.PRICE = MAX(FP1.PRICE)) AS PRODUCT_NAME
FROM FOOD_PRODUCT FP1
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC;